sudo: false
language: node_js
node_js:
  - "stable"
  - 12
  - 11
  - 10
  - 9
  - 8
  - 7
cache:
  directories:
    - node_modules
before_script:
  - npm prune
script:
  - npm run test-cov
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov
